### ISSUE TITLE
Firefox + Greasemonkey: Settings menu not working

### ISSUE THREAD

**Issue by leodoi3** [Purfview/IMDb-Scout-Mod#10]
Firefox 84.0.1 64bit
I cannot open settings from the right-click menu and nothing happens. I tried disabling ad-blocker , disabling other extensions, and re-installing.

**Comment by Purfview** [comment]
Greasemonkey's creates context menu and it works on other browsers (eg Waterfox), but doesn't  on Firefox.
Violentmonkey and Tampermonkey have menu in a plugin and works for all browsers. 

Change browser or change monkey, or both, there is better browsers than Firefox and there is better Monkeys than Greasemonkey...

Here is the issue:
https://github.com/greasemonkey/greasemonkey/issues/3078

**Comment by poke** [comment]
This seems unrelated to the `registerMenuCommand` function because:

- Clicking the temporary button “Load Settings” will also do nothing (the button just disappears). So it is likely that just the `GM_config.open()` fails.
- The “unit test” for `GM_config` actually fails for me on GM4 too: https://openuserjs.org/scripts/sizzle/The_GM_config_Unit_Test

So I would suggest you to bring this up with the GM_config authors because apparently that doesn’t work with GM4.

**Comment by poke** [comment]
Yes, this is an issue with GM_config and GM4. The following code won’t work with GM4 at the moment:

```js
var iframe = document.createElement('iframe');
iframe.src = 'about:blank';
document.body.appendChild(iframe);
iframe.addEventListener('load', function() {
    console.log('iframe.contentDocument', this.contentDocument);
});
```

But that’s what GM_config uses to render its config screen.

**Comment by Purfview** [comment]
> 
> 
> Yes, this is an issue with GM_config and GM4. The following code won’t work with GM4 at the moment:

Strangely, GM_config and GM4 works on Waterfox Classic, GM3 works too.

**Comment by poke** [comment]
I can only assume that Waterfox doesn’t follow the same-origin rulings for [contentDocument](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument) in the same way then. GM3 is a _very different_ beast that has little to do with how GM4 works.

**Comment by Purfview** [comment]
Should be fixed now.
Thanks to @poke and @Martii.
