### ISSUE TITLE
Interval between consecutive searches on IMDb lists

### ISSUE THREAD

**Issue by Xazmah** [Purfview/IMDb-Scout-Mod#17]
When visiting an imdb list the script start searching the titles one after the other without respecting each website or forum searches intervals this result in indicating that no results are found or sometimes getting banned for the flood like RARBG ban you for 24 hours

Here's a list of limits i know of

forum.snahp -- 20 seconds interval
warezforums -- 5 seconds interval

**Comment by Purfview** [comment]
Script respects websites and by default doesn't make more than 1 search per 0.8 second on IMDb lists.
If some site needs bigger limit then it can be changed by 'rateLimit'.

Checks:

============================
RARBG with 5s limit - good.
RARBG with 2s limit - ban for 2h (not 24h).
Later I'll test for more precise threshold of the limit.
Btw, site wrote "You are making more than 10 requests per second to the site" which is not true.
============================

WF with 5s limit - few red icons.
WF with 5.2s limit - all good.
============================

Snahp I can't check because I'm not there, and I think it was reported somewhere that entry doesn't work correctly.

**Comment by Xazmah** [comment]
>Snahp I can't check because I'm not there

I can confirm that it's 20 seconds for most users (maybe less for donors/uploaders/elites/vips) and 1 second if you buyed Quick Search perk from shop

**Comment by Purfview** [comment]
Should be fixed in v8.5.
