### ISSUE TITLE
feature request: adding www.themoviedb.org support?

### ISSUE THREAD

**Issue by rezad1393** [Purfview/IMDb-Scout-Mod#71]
the website it more community oriented than the company owned imdb.
it is not as big and has less data but users can add the data themselves.
it has a open access api (which imdb doesnt have) and the data is community owned and can be accessed via api.

even though it is smaller right now I have seen some movies that have tmdb pages but not imdb pages.

can you add support for running this script on the tmdb pages too? or is this script too imdb oriented to be worth it?

right now the torrent sites that support tmdb that I know are the cinemaz family (privatehd and avistaz).

**Comment by Purfview** [comment]
1) This script is for IMDb site, so you are asking for another script. TMDb ID's are supported by the script already.
2) IMDb data is added by users, same as TMDb, so you can add data yourself there too.
3) TMDb data is not owned by community.
4) IMDb doesn't need API because it shares it's database publicly, so you even don't need to connect to IMDb.
5) Now there's no point of the script for TMDb as only handful of sites use it, and its data is no match for IMDb yet.

**Comment by rezad1393** [comment]
1- I said that too.
2- yes and no. there are data added by user and there are data added by companies (which also dovetails in imdb pro)
3- it data is. as in they can not stop you from using all the data as you wish. kinda like a semi open source app. but databases are governed differently (even between USA and Europe). but imdb data is owned by imdb company, which mean the data that a user enters it not own by the user or owned by other but by imdb.
4- imdb shared its database publicly? where? if it did then tmdb would just download it and import it.
5- that is a valid point. and the whole point of this feature request was to see it a new script was possible.
1/5 tmdb ids in scirpt works  how if it doesnt run on tmdb and only on imdb?

**Comment by Purfview** [comment]
1) No, you didn't.
2) Good to know that IMDb is twice better than TMDb. :)
3) Wrong.
4) Wrong.
3/4) Then where is TMDb data to download? Ah there is no such. TMDb is for "for personal and non-commercial use" too.
5) Everything is possible if it's not a fantasy.
1/5) Because these are two different websites.

No need to fantasize about things if you don't understand what the intellectual property is and how copyright or programs work. 
And this is not a place to ask for the new scripts, learn programming and write one yourself.

**Comment by rezad1393** [comment]
sorry if I offended you.
I have read the data policy of both imdb and tmdb and there is differences between them that give more freedom to users.
https://developers.themoviedb.org/3/getting-started/daily-file-exports
this is just the first one I found for export.

adding data by companies is twice as good if you can then use it freely not if it is copyrighted.

4- just wrong? seriously ? did I anger you? did I insult you that you give this kind of answers?
I would have understood the "wrong" one word answer for point 3 based on difference understanding of the issue, but 4 too?
are you saying "wrong" as in tdmb CAN import imdn data legally? or are you saying not being able to import it is a .... good thing? a user freedom preserving thing?

maybe all got confused over wire and ( I have no idea why) you got insulted by me.
if so I apologize.

i will unsubscribe from this so that this issue wont fester more.

**Comment by Purfview** [comment]
Sorry, but I can't understand what you are trying to say.
Let's start from simple question: How all that is relevant to this script?

If you don't like short answers then you should find appropriate places where you can get better answers. I have no interest in these topics and here is not a place to learn about laws or copyright nor programming.

I can't be offended by anything on internet, but it looks like you was offended by my sarcasm, don't be. :)
If I wanted to chat about random stuff on internet then I would have the reddit's account, definitively I wouln't do it on the GitHub's issues pages.
